title: Bio131 Spring 2024
description: Introduction to Computational Biology at Reed College
theme: just-the-docs

url: https://reed-compbio-classes.github.io/

aux_links:
  S24 Moodle: https://moodle.reed.edu/course/view.php?id=5287
