title: Bio131 Spring 2024
description: Introduction to Computational Biology at Reed College
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Moodle: https://moodle.reed.edu/course/view.php?id=5287
